### ISSUE TITLE
Grades view

### ISSUE THREAD

**Issue by ipozow** [Incubadora-de-Ases/AppDocumentation#39]
As a student, I want to see all my grades

——

Dashboard -> Estadísticas -> First button of Más detalles

Here the grade should be the average of the courses. 
Click on the course. 
<img width="1163" alt="Captura de Pantalla 2022-03-02 a la(s) 17 46 30" src="https://user-images.githubusercontent.com/10505413/156449960-763b9b42-8654-4b94-95de-0e25249aa5cb.png">

Here the grade should be the average of the subjects.
Click on the subject
<img width="1163" alt="Captura de Pantalla 2022-03-02 a la(s) 17 46 30" src="https://user-images.githubusercontent.com/10505413/156451622-cfb59435-5914-4d0e-a3be-f5b3343a4287.png">

Here the grade should be the average of the tests. 
<img width="1163" alt="Captura de Pantalla 2022-03-02 a la(s) 17 46 30" src="https://user-images.githubusercontent.com/10505413/156451974-115b6e83-f09b-487c-88ad-9fa8dbbe5a5d.png">

Test are calculated #40 

The subject comes from there: 
<img width="1163" alt="Captura de Pantalla 2022-03-02 a la(s) 18 17 58" src="https://user-images.githubusercontent.com/10505413/156451234-bc42c23e-856b-40e5-8ef7-777a128d1ba4.png">
The test name comes from here: 
<img width="1163" alt="Captura de Pantalla 2022-03-02 a la(s) 18 18 04" src="https://user-images.githubusercontent.com/10505413/156451245-70a7112e-72b7-46af-8e90-a918dce91c17.png">

**Comment by kathayatnk** [comment]
@ipozow The points from questions are set to 0. Are the points for questions set from teachers app? Please confirm the points are not 0.
