### ISSUE TITLE
Grades

### ISSUE THREAD

**Issue by ipozow** [Incubadora-de-Ases/AppDocumentation#40]
Grades should be calculated the following way: 

((Sum of all question's max score)/(Sum of all question's max score))*7

Example: 
Question 1 max score: 10
Question 2 max score: 20
Question 3 max score: 15

Student scores: 

Question 1: 10
Question 2: 10
Question 3: 10

Calculation: 

((10+10+10)/(10+20+15)) * 7

(30 ÷ 45) * 7 = 4,67

**Context** 
Teachers can create tests. Every question has a score.

**Comment by kathayatnk** [comment]
@ipozow The questions when created have 0 points. I've updated the formula to calculate the average, however without points we will only see 0 as average in app.
