### ISSUE TITLE
Not showing third image if there is an image and a paragraph before

### ISSUE THREAD

**Issue by ipozow** [Incubadora-de-Ases/AppDocumentation#43]
The app should show
Image
Paragraph
Image

But the app is only showing 
Image
Paragraph

<img width="1163" alt="Captura de Pantalla 2022-03-03 a la(s) 12 54 30" src="https://user-images.githubusercontent.com/10505413/156601433-04fe3ac6-3113-4ed6-8e26-76f3722cd1f4.png">

**Comment by kathayatnk** [comment]
@ipozow There seems to be a problem with the image name stored in DB for this screen and lesson. I've added some fixes for the downloading mechanism, however the image for this screen doesn't seems to exists. log from Firebase Storage.

**1646322127354Captura de Pantalla 2022-03-03 a la(s) 12.41.07.png** does not exist
