### ISSUE TITLE
Showing images that shouldn't be shown

### ISSUE THREAD

**Issue by ipozow** [Incubadora-de-Ases/AppDocumentation#44]
<img width="1278" alt="Captura de Pantalla 2022-03-26 a la(s) 22 58 27" src="https://user-images.githubusercontent.com/10505413/160263381-9f9df09d-7d38-4325-a640-ca6cef8e5c6e.png">

For some reason there is a image in FirstImage, but there can't be an image and a paragraph. It's image OR paragraph.

**Comment by kathayatnk** [comment]
@ipozow  I've looked into the data and they seems to be coming from different app. This needs to be checked from there.
